// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [AuthorizeEnvironment][google.cloud.shell.v1.CloudShellService.AuthorizeEnvironment].
///
/// [google.cloud.shell.v1.CloudShellService.AuthorizeEnvironment]: <doc:CloudShellServiceClient/authorizeEnvironment(request:options:)>
public struct AuthorizeEnvironmentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the resource that should receive the credentials, for example
  /// `users/me/environments/default` or
  /// `users/someone@example.com/environments/default`.
  public var name: Swift.String = Swift.String()

  /// The OAuth access token that should be sent to the environment.
  public var accessToken: Swift.String = Swift.String()

  /// The OAuth ID token that should be sent to the environment.
  public var idToken: Swift.String = Swift.String()

  /// The time when the credentials expire. If not set, defaults to one hour from
  /// when the server received the request.
  public var expireTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthorizeEnvironmentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthorizeEnvironmentRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let accessToken = CodingKeys(stringValue: "accessToken")
    static let idToken = CodingKeys(stringValue: "idToken")
    static let expireTime = CodingKeys(stringValue: "expireTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "accessToken",
      "idToken",
      "expireTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accessToken) {
      self.accessToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .idToken) {
      self.idToken = value
    }
    self.expireTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .expireTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.accessToken, forKey: .accessToken)
    try container.encode(self.idToken, forKey: .idToken)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.AuthorizeEnvironmentRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
