// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [AuthorizeEnvironment][google.cloud.shell.v1.CloudShellService.AuthorizeEnvironment].
///
/// [google.cloud.shell.v1.CloudShellService.AuthorizeEnvironment]: <doc:CloudShellServiceClient/authorizeEnvironment(request:options:)>
public struct AuthorizeEnvironmentRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of the resource that should receive the credentials, for example
  /// `users/me/environments/default` or
  /// `users/someone@example.com/environments/default`.
  public var name: Swift.String = Swift.String()

  /// The OAuth access token that should be sent to the environment.
  public var accessToken: Swift.String = Swift.String()

  /// The OAuth ID token that should be sent to the environment.
  public var idToken: Swift.String = Swift.String()

  /// The time when the credentials expire. If not set, defaults to one hour from
  /// when the server received the request.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `AuthorizeEnvironmentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthorizeEnvironmentRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.AuthorizeEnvironmentRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
