// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// API for interacting with Google Cloud Shell. Each user of Cloud Shell has at
/// least one environment, which has the ID "default". Environment consists of a
/// Docker image defining what is installed on the environment and a home
/// directory containing the user's data that will remain across sessions.
/// Clients use this API to start and fetch information about their environment,
/// which can then be used to connect to that environment via a separate SSH
/// client.
///
/// @Snippet(path: "CloudShellServiceQuickstart")
public class CloudShellServiceClient: Clients.CloudShellServiceProtocol {
  let inner: any Clients.CloudShellServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `CloudShellServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudShellServiceStub = try Clients.CloudShellServiceTransport(options)
    inner = Clients.CloudShellServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudShellServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Gets an environment. Returns NOT_FOUND if the environment does not exist.
  ///
  /// @Snippet(path: "CloudShellService_GetEnvironment")
  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudShellV1.Environment {
    try await self.inner.getEnvironment(request: request, options: options)
  }

  /// Starts an existing environment, allowing clients to connect to it. The
  /// returned operation will contain an instance of StartEnvironmentMetadata in
  /// its metadata field. Users can wait for the environment to start by polling
  /// this operation via GetOperation. Once the environment has finished starting
  /// and is ready to accept connections, the operation will contain a
  /// StartEnvironmentResponse in its response field.
  ///
  /// @Snippet(path: "CloudShellService_StartEnvironment")
  public func startEnvironment(
    request: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startEnvironment(request: request, options: options)
  }

  /// Starts an existing environment, allowing clients to connect to it. The
  /// returned operation will contain an instance of StartEnvironmentMetadata in
  /// its metadata field. Users can wait for the environment to start by polling
  /// this operation via GetOperation. Once the environment has finished starting
  /// and is ready to accept connections, the operation will contain a
  /// StartEnvironmentResponse in its response field.
  ///
  /// @Snippet(path: "CloudShellService_StartEnvironment")
  public func startEnvironment(
    withPolling: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<StartEnvironmentResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<StartEnvironmentResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try StartEnvironmentResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.startEnvironment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<StartEnvironmentResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Sends OAuth credentials to a running environment on behalf of a user. When
  /// this completes, the environment will be authorized to run various Google
  /// Cloud command line tools without requiring the user to manually
  /// authenticate.
  ///
  /// @Snippet(path: "CloudShellService_AuthorizeEnvironment")
  public func authorizeEnvironment(
    request: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.authorizeEnvironment(request: request, options: options)
  }

  /// Sends OAuth credentials to a running environment on behalf of a user. When
  /// this completes, the environment will be authorized to run various Google
  /// Cloud command line tools without requiring the user to manually
  /// authenticate.
  ///
  /// @Snippet(path: "CloudShellService_AuthorizeEnvironment")
  public func authorizeEnvironment(
    withPolling: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AuthorizeEnvironmentResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AuthorizeEnvironmentResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AuthorizeEnvironmentResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.authorizeEnvironment(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<AuthorizeEnvironmentResponse>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Adds a public SSH key to an environment, allowing clients with the
  /// corresponding private key to connect to that environment via SSH. If a key
  /// with the same content already exists, this will error with ALREADY_EXISTS.
  ///
  /// @Snippet(path: "CloudShellService_AddPublicKey")
  public func addPublicKey(
    request: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.addPublicKey(request: request, options: options)
  }

  /// Adds a public SSH key to an environment, allowing clients with the
  /// corresponding private key to connect to that environment via SSH. If a key
  /// with the same content already exists, this will error with ALREADY_EXISTS.
  ///
  /// @Snippet(path: "CloudShellService_AddPublicKey")
  public func addPublicKey(
    withPolling: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddPublicKeyResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddPublicKeyResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AddPublicKeyResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.addPublicKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<AddPublicKeyResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Removes a public SSH key from an environment. Clients will no longer be
  /// able to connect to the environment using the corresponding private key.
  /// If a key with the same content is not present, this will error with
  /// NOT_FOUND.
  ///
  /// @Snippet(path: "CloudShellService_RemovePublicKey")
  public func removePublicKey(
    request: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.removePublicKey(request: request, options: options)
  }

  /// Removes a public SSH key from an environment. Clients will no longer be
  /// able to connect to the environment using the corresponding private key.
  /// If a key with the same content is not present, this will error with
  /// NOT_FOUND.
  ///
  /// @Snippet(path: "CloudShellService_RemovePublicKey")
  public func removePublicKey(
    withPolling: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<RemovePublicKeyResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<RemovePublicKeyResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try RemovePublicKeyResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.removePublicKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<RemovePublicKeyResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudShellService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudShellServiceClient`.
  ///
  /// To mock `CloudShellServiceClient` change your functions to receive
  /// `some CloudShellServiceProtocol` or `any CloudShellServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudShellServiceProtocol {
    /// See `CloudShellServiceClient.getEnvironment`.
    func getEnvironment(request: GetEnvironmentRequest) async throws
      -> GoogleCloudShellV1.Environment

    /// See `CloudShellServiceClient.getEnvironment`.
    func getEnvironment(
      name: Swift.String,
    ) async throws -> GoogleCloudShellV1.Environment

    /// See `CloudShellServiceClient.startEnvironment`.
    func startEnvironment(request: StartEnvironmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.startEnvironment`.
    func startEnvironment(withPolling: StartEnvironmentRequest) async throws -> any GoogleCloudGax
      .PollableOperation<StartEnvironmentResponse>

    /// See `CloudShellServiceClient.authorizeEnvironment`.
    func authorizeEnvironment(request: AuthorizeEnvironmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.authorizeEnvironment`.
    func authorizeEnvironment(withPolling: AuthorizeEnvironmentRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AuthorizeEnvironmentResponse>

    /// See `CloudShellServiceClient.addPublicKey`.
    func addPublicKey(request: AddPublicKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.addPublicKey`.
    func addPublicKey(withPolling: AddPublicKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AddPublicKeyResponse>

    /// See `CloudShellServiceClient.removePublicKey`.
    func removePublicKey(request: RemovePublicKeyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.removePublicKey`.
    func removePublicKey(withPolling: RemovePublicKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<RemovePublicKeyResponse>

    /// See `CloudShellServiceClient.getEnvironment`.
    func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudShellV1.Environment

    /// See `CloudShellServiceClient.startEnvironment`.
    func startEnvironment(
      request: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.startEnvironment`.
    func startEnvironment(
      withPolling: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<StartEnvironmentResponse>

    /// See `CloudShellServiceClient.authorizeEnvironment`.
    func authorizeEnvironment(
      request: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.authorizeEnvironment`.
    func authorizeEnvironment(
      withPolling: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AuthorizeEnvironmentResponse>

    /// See `CloudShellServiceClient.addPublicKey`.
    func addPublicKey(
      request: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.addPublicKey`.
    func addPublicKey(
      withPolling: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddPublicKeyResponse>

    /// See `CloudShellServiceClient.removePublicKey`.
    func removePublicKey(
      request: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudShellServiceClient.removePublicKey`.
    func removePublicKey(
      withPolling: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<RemovePublicKeyResponse>
  }
}

// Default implementations
extension Clients.CloudShellServiceProtocol {
  public func getEnvironment(request: GetEnvironmentRequest) async throws
    -> GoogleCloudShellV1.Environment
  {
    try await self.getEnvironment(request: request, options: .init())
  }

  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudShellV1.Environment {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEnvironment(
    name: Swift.String,
  ) async throws -> GoogleCloudShellV1.Environment {
    let request = GetEnvironmentRequest().with {
      $0.name = name
    }
    return try await self.getEnvironment(request: request)
  }

  public func startEnvironment(request: StartEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.startEnvironment(request: request, options: .init())
  }

  public func startEnvironment(
    request: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func startEnvironment(withPolling: StartEnvironmentRequest) async throws
    -> any GoogleCloudGax.PollableOperation<StartEnvironmentResponse>
  {
    try await self.startEnvironment(withPolling: withPolling, options: .init())
  }

  public func startEnvironment(
    withPolling: StartEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<StartEnvironmentResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<StartEnvironmentResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func authorizeEnvironment(request: AuthorizeEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.authorizeEnvironment(request: request, options: .init())
  }

  public func authorizeEnvironment(
    request: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func authorizeEnvironment(withPolling: AuthorizeEnvironmentRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AuthorizeEnvironmentResponse>
  {
    try await self.authorizeEnvironment(withPolling: withPolling, options: .init())
  }

  public func authorizeEnvironment(
    withPolling: AuthorizeEnvironmentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AuthorizeEnvironmentResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<AuthorizeEnvironmentResponse>.State
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func addPublicKey(request: AddPublicKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.addPublicKey(request: request, options: .init())
  }

  public func addPublicKey(
    request: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func addPublicKey(withPolling: AddPublicKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<AddPublicKeyResponse>
  {
    try await self.addPublicKey(withPolling: withPolling, options: .init())
  }

  public func addPublicKey(
    withPolling: AddPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddPublicKeyResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<AddPublicKeyResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func removePublicKey(request: RemovePublicKeyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.removePublicKey(request: request, options: .init())
  }

  public func removePublicKey(
    request: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func removePublicKey(withPolling: RemovePublicKeyRequest) async throws
    -> any GoogleCloudGax.PollableOperation<RemovePublicKeyResponse>
  {
    try await self.removePublicKey(withPolling: withPolling, options: .init())
  }

  public func removePublicKey(
    withPolling: RemovePublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<RemovePublicKeyResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<RemovePublicKeyResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
