// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Cloud-shell specific information that will be included as details in failure
/// responses.
public struct CloudShellErrorDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Code indicating the specific error the occurred.
  public var code: CloudShellErrorDetails.CloudShellErrorCode =
    CloudShellErrorDetails.CloudShellErrorCode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudShellErrorDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudShellErrorDetails().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let code = CodingKeys(stringValue: "code")

    static let _knownKeys: Set<Swift.String> = [
      "code"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      CloudShellErrorDetails.CloudShellErrorCode.self, forKey: .code)
    {
      self.code = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.code, forKey: .code)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Set of possible errors returned from API calls.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CloudShellErrorCode: Codable, Equatable, Sendable {
    /// An unknown error occurred.
    case unspecified
    /// The image used by the Cloud Shell environment either does not exist or
    /// the user does not have access to it.
    case imageUnavailable
    /// Cloud Shell has been disabled by an administrator for the user making the
    /// request.
    case cloudShellDisabled
    /// Cloud Shell has been permanently disabled due to a Terms of Service
    /// violation by the user.
    case tosViolation
    /// The user has exhausted their weekly Cloud Shell quota, and Cloud Shell
    /// will be disabled until the quota resets.
    case quotaExceeded
    /// The Cloud Shell environment is unavailable and cannot be connected to at
    /// the moment.
    case environmentUnavailable
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .imageUnavailable: return 1
      case .cloudShellDisabled: return 2
      case .tosViolation: return 4
      case .quotaExceeded: return 5
      case .environmentUnavailable: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_SHELL_ERROR_CODE_UNSPECIFIED"
      case .imageUnavailable: return "IMAGE_UNAVAILABLE"
      case .cloudShellDisabled: return "CLOUD_SHELL_DISABLED"
      case .tosViolation: return "TOS_VIOLATION"
      case .quotaExceeded: return "QUOTA_EXCEEDED"
      case .environmentUnavailable: return "ENVIRONMENT_UNAVAILABLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudShellErrorCode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_SHELL_ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "IMAGE_UNAVAILABLE": self = .imageUnavailable
      case "CLOUD_SHELL_DISABLED": self = .cloudShellDisabled
      case "TOS_VIOLATION": self = .tosViolation
      case "QUOTA_EXCEEDED": self = .quotaExceeded
      case "ENVIRONMENT_UNAVAILABLE": self = .environmentUnavailable
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudShellErrorCode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .imageUnavailable
      case 2: self = .cloudShellDisabled
      case 4: self = .tosViolation
      case 5: self = .quotaExceeded
      case 6: self = .environmentUnavailable
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLOUD_SHELL_ERROR_CODE_UNSPECIFIED")
      case .imageUnavailable: return try container.encode("IMAGE_UNAVAILABLE")
      case .cloudShellDisabled: return try container.encode("CLOUD_SHELL_DISABLED")
      case .tosViolation: return try container.encode("TOS_VIOLATION")
      case .quotaExceeded: return try container.encode("QUOTA_EXCEEDED")
      case .environmentUnavailable: return try container.encode("ENVIRONMENT_UNAVAILABLE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.CloudShellErrorDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
