// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Cloud-shell specific information that will be included as details in failure
/// responses.
public struct CloudShellErrorDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Code indicating the specific error the occurred.
  public var code: CloudShellErrorDetails.CloudShellErrorCode =
    CloudShellErrorDetails.CloudShellErrorCode()

  /// Initialize a new instance of `CloudShellErrorDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudShellErrorDetails().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Set of possible errors returned from API calls.
  public enum CloudShellErrorCode: Codable, Equatable, Sendable {
    /// An unknown error occurred.
    case unspecified
    /// The image used by the Cloud Shell environment either does not exist or
    /// the user does not have access to it.
    case imageUnavailable
    /// Cloud Shell has been disabled by an administrator for the user making the
    /// request.
    case cloudShellDisabled
    /// Cloud Shell has been permanently disabled due to a Terms of Service
    /// violation by the user.
    case tosViolation
    /// The user has exhausted their weekly Cloud Shell quota, and Cloud Shell
    /// will be disabled until the quota resets.
    case quotaExceeded
    /// The Cloud Shell environment is unavailable and cannot be connected to at
    /// the moment.
    case environmentUnavailable
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .imageUnavailable: return 1
      case .cloudShellDisabled: return 2
      case .tosViolation: return 4
      case .quotaExceeded: return 5
      case .environmentUnavailable: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_SHELL_ERROR_CODE_UNSPECIFIED"
      case .imageUnavailable: return "IMAGE_UNAVAILABLE"
      case .cloudShellDisabled: return "CLOUD_SHELL_DISABLED"
      case .tosViolation: return "TOS_VIOLATION"
      case .quotaExceeded: return "QUOTA_EXCEEDED"
      case .environmentUnavailable: return "ENVIRONMENT_UNAVAILABLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudShellErrorCode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_SHELL_ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "IMAGE_UNAVAILABLE": self = .imageUnavailable
      case "CLOUD_SHELL_DISABLED": self = .cloudShellDisabled
      case "TOS_VIOLATION": self = .tosViolation
      case "QUOTA_EXCEEDED": self = .quotaExceeded
      case "ENVIRONMENT_UNAVAILABLE": self = .environmentUnavailable
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudShellErrorCode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .imageUnavailable
      case 2: self = .cloudShellDisabled
      case 4: self = .tosViolation
      case 5: self = .quotaExceeded
      case 6: self = .environmentUnavailable
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .imageUnavailable: return try container.encode(1)
      case .cloudShellDisabled: return try container.encode(2)
      case .tosViolation: return try container.encode(4)
      case .quotaExceeded: return try container.encode(5)
      case .environmentUnavailable: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.CloudShellErrorDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
