// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Cloud Shell environment, which is defined as the combination of a Docker
/// image specifying what is installed on the environment and a home directory
/// containing the user's data that will remain across sessions. Each user has
/// at least an environment with the ID "default".
public struct Environment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. Full name of this resource, in the format
  /// `users/{owner_email}/environments/{environment_id}`. `{owner_email}` is the
  /// email address of the user to whom this environment belongs, and
  /// `{environment_id}` is the identifier of this environment. For example,
  /// `users/someone@example.com/environments/default`.
  public var name: Swift.String = Swift.String()

  /// Output only. The environment's identifier, unique among the user's
  /// environments.
  public var id: Swift.String = Swift.String()

  /// Required. Immutable. Full path to the Docker image used to run this environment, e.g.
  /// "gcr.io/dev-con/cloud-devshell:latest".
  public var dockerImage: Swift.String = Swift.String()

  /// Output only. Current execution state of this environment.
  public var state: Environment.State = Environment.State()

  /// Output only. Host to which clients can connect to initiate HTTPS or WSS
  /// connections with the environment.
  public var webHost: Swift.String = Swift.String()

  /// Output only. Username that clients should use when initiating SSH sessions
  /// with the environment.
  public var sshUsername: Swift.String = Swift.String()

  /// Output only. Host to which clients can connect to initiate SSH sessions
  /// with the environment.
  public var sshHost: Swift.String = Swift.String()

  /// Output only. Port to which clients can connect to initiate SSH sessions
  /// with the environment.
  public var sshPort: Swift.Int32 = Swift.Int32()

  /// Output only. Public keys associated with the environment. Clients can
  /// connect to this environment via SSH only if they possess a private key
  /// corresponding to at least one of these public keys. Keys can be added to or
  /// removed from the environment using the AddPublicKey and RemovePublicKey
  /// methods.
  public var publicKeys: [Swift.String] = []

  /// Initialize a new instance of `Environment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Environment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible execution states for an environment.
  public enum State: Codable, Equatable, Sendable {
    /// The environment's states is unknown.
    case unspecified
    /// The environment is not running and can't be connected to. Starting the
    /// environment will transition it to the PENDING state.
    case suspended
    /// The environment is being started but is not yet ready to accept
    /// connections.
    case pending
    /// The environment is running and ready to accept connections. It will
    /// automatically transition back to DISABLED after a period of inactivity or
    /// if another environment is started.
    case running
    /// The environment is being deleted and can't be connected to.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .suspended: return 1
      case .pending: return 2
      case .running: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .suspended: return "SUSPENDED"
      case .pending: return "PENDING"
      case .running: return "RUNNING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SUSPENDED": self = .suspended
      case "PENDING": self = .pending
      case "RUNNING": self = .running
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .suspended
      case 2: self = .pending
      case 3: self = .running
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .suspended: return try container.encode(1)
      case .pending: return try container.encode(2)
      case .running: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.Environment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
