// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message included in the metadata field of operations returned from
/// [StartEnvironment][google.cloud.shell.v1.CloudShellService.StartEnvironment].
///
/// [google.cloud.shell.v1.CloudShellService.StartEnvironment]: <doc:CloudShellServiceClient/startEnvironment(request:)>
public struct StartEnvironmentMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Current state of the environment being started.
  public var state: StartEnvironmentMetadata.State = StartEnvironmentMetadata.State()

  /// Initialize a new instance of `StartEnvironmentMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StartEnvironmentMetadata().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible states an environment might transition between during startup.
  /// These states are not normally actionable by clients, but may be used to
  /// show a progress message to the user. An environment won't necessarily go
  /// through all of these states when starting. More states are likely to be
  /// added in the future.
  public enum State: Codable, Equatable, Sendable {
    /// The environment's start state is unknown.
    case unspecified
    /// The environment is in the process of being started, but no additional
    /// details are available.
    case starting
    /// Startup is waiting for the user's disk to be unarchived. This can happen
    /// when the user returns to Cloud Shell after not having used it for a
    /// while, and suggests that startup will take longer than normal.
    case unarchivingDisk
    /// Startup has completed. If the start operation was successful, the user
    /// should be able to establish an SSH connection to their environment.
    /// Otherwise, the operation will contain details of the failure.
    case finished
    /// Startup is waiting for compute resources to be assigned to the
    /// environment. This should normally happen very quickly, but an environment
    /// might stay in this state for an extended period of time if the system is
    /// experiencing heavy load.
    case awaitingComputeResources
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .starting: return 1
      case .unarchivingDisk: return 2
      case .finished: return 3
      case .awaitingComputeResources: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .starting: return "STARTING"
      case .unarchivingDisk: return "UNARCHIVING_DISK"
      case .finished: return "FINISHED"
      case .awaitingComputeResources: return "AWAITING_COMPUTE_RESOURCES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STARTING": self = .starting
      case "UNARCHIVING_DISK": self = .unarchivingDisk
      case "AWAITING_COMPUTE_RESOURCES": self = .awaitingComputeResources
      case "FINISHED": self = .finished
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .starting
      case 2: self = .unarchivingDisk
      case 3: self = .finished
      case 4: self = .awaitingComputeResources
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .starting: return try container.encode(1)
      case .unarchivingDisk: return try container.encode(2)
      case .finished: return try container.encode(3)
      case .awaitingComputeResources: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.shell.v1.StartEnvironmentMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
